# Generated by Django 2.0.3 on 2018-06-09 21:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20180609_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='描述'),
        ),
    ]
