# Generated by Django 2.0.3 on 2018-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180605_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='视频地址'),
        ),
    ]
